### ISSUE TITLE
[Mod Support Request] Sawmill

### ISSUE THREAD

**Issue by sonliviiy** [nebuIr/Default-Dark-Mode#218]
### Description

![2024-09-21_22 52 25](https://github.com/user-attachments/assets/3658a39a-3307-41e9-9baf-2b579a1a3783)

### Link to the mod page

https://modrinth.com/mod/universal-sawmill

### Game versions

1.20, 1.19

### Mod Loaders

Fabric, Forge, NeoForge

**Comment by aricloverEXTRA** [comment]
Hey @sonliviiy I know this issue was closed months ago but I forgot to mention that I have a resource pack called **Default Dark Mode: Expansion”** that includes **Sawmill** mod support. https://modrinth.com/resourcepack/default-dark-mode-expansion

and I do hope NebuIr adds that in onto this GitHub repository soon.
